export const projects = [
  {
    title: "ChannelIQ | Enterprise Communication Platform",
    slug: "channeliq-enterprise-communication-platform",
    tagline:
      "A comprehensive enterprise communication platform built with microservices, real-time messaging, video conferencing, and professional networking.",
    overview:
      "ChannelIQ is an enterprise-grade communication and collaboration system for corporate teams. It is built using a microservices architecture with an API gateway and dedicated services for authentication, user management, chat, media, and meetings. The platform supports secure auth flows, real-time messaging, group collaboration, file sharing, and LiveKit-powered video conferencing, while using Redis and Kafka for scalable distributed communication.",
    features: [
      "Secure JWT authentication with HTTP-only cookies, OTP verification, and Redis-backed sessions.",
      "Real-time messaging with Socket.IO including typing indicators, reactions, pinning, and group announcements.",
      "Role-based group management with Admin, Co-Admin, and Member permissions.",
      "LiveKit-powered HD video meetings with participant management and screen sharing.",
      "Media upload pipeline with validation, presigned URLs, and cloud storage support.",
      "Event-driven service communication using Kafka topics for cross-service workflows.",
      "Containerized deployment using Docker Compose, plus Kubernetes manifests and a Helm chart for repeatable multi-service orchestration.",
      "Ingress-based routing and monitoring-ready setup for Prometheus/Grafana in cluster environments.",
    ],
    techStack: [
      "React 19",
      "TypeScript",
      "Redux Toolkit",
      "Socket.IO",
      "Node.js",
      "Express",
      "Prisma",
      "PostgreSQL",
      "Redis",
      "Kafka",
      "LiveKit",
      "Docker",
      "Kubernetes",
      "Helm",
    ],
    challenges: [
      "Designing clear service boundaries and API contracts across multiple independent services.",
      "Maintaining reliable real-time messaging and event consistency between Socket.IO and Kafka workflows.",
      "Handling secure authentication and session management across distributed services.",
      "Managing deployment complexity for multi-service environments with Docker, Kubernetes, Helm values, and environment-specific configuration.",
    ],
    learnings: [
      "Gained hands-on experience building and scaling a production-style microservices architecture.",
      "Improved skills in distributed system design, asynchronous communication, and event-driven patterns.",
      "Deepened understanding of infrastructure concerns including containerization, Kubernetes service orchestration, ingress design, and Helm-based release management.",
      "Strengthened knowledge of secure auth, API hardening, and collaborative enterprise product design.",
    ],
    feedback: false,
    links: {
      live: "",
      github: "https://github.com/CodeSahil21/ChannelIQ.git",
    },
  },

  {
    title: "VendorClause-ai | PolyGot",
    slug: "vendorclause-ai-polygot",
    tagline:
      "An end-to-end AI document intelligence platform for legal-style workflows with async ingestion, hybrid retrieval, and streaming source-grounded answers.",
    overview:
      "PolyGot (VendorClause-ai) is a multi-service AI platform for legal and compliance document workflows. It provides secure auth and session management, PDF upload with asynchronous ingestion, hybrid retrieval across vector and graph stores, and source-grounded streaming chat answers. The monorepo is organized into client, Gateway, and ai-service modules, with Docker Compose orchestration for local infrastructure such as Postgres, Redis, MinIO, Qdrant, Neo4j, MongoDB, Ollama, and Langfuse.",
    features: [
      "Secure authentication and session management through the Gateway service.",
      "PDF upload with async ingestion pipeline using queues and worker processing.",
      "Hybrid retrieval pipeline combining Qdrant vector search and Neo4j graph traversal.",
      "Streaming, source-grounded chat answers delivered via Redis pub/sub and Socket.IO.",
      "Dedicated MCP servers for Qdrant and Neo4j tool access in retrieval workflows.",
      "LangGraph-based retrieval workflow with supervisor, rewriting, orchestration, fusion, CRAG evaluation, and generation stages.",
      "End-to-end local environment with Docker Compose and service-level observability.",
      "Demo video support embedded directly from repository docs.",
    ],
    techStack: [
      "Next.js 16",
      "React 19",
      "TypeScript",
      "Zustand",
      "Socket.IO",
      "Node.js",
      "Express",
      "Prisma",
      "BullMQ",
      "Redis",
      "MinIO",
      "Python",
      "LangGraph",
      "LangChain",
      "LlamaParse",
      "Qdrant",
      "Neo4j",
      "Docker Compose",
    ],
    challenges: [
      "Coordinating ingestion and retrieval across multiple services while preserving reliable async state transitions.",
      "Designing low-latency streaming UX from query workers through Redis channels and Gateway Socket.IO bridges.",
      "Balancing vector and graph retrieval quality for legal-style, source-sensitive answers.",
      "Managing local developer experience across many infra dependencies and service processes.",
    ],
    learnings: [
      "Improved system design skills for AI-first, event-driven multi-service applications.",
      "Deepened hands-on understanding of retrieval orchestration with LangGraph and MCP servers.",
      "Strengthened deployment and debugging practices for complex local stacks using Docker Compose.",
      "Built stronger patterns for source-grounded answer generation and stream-based product UX.",
    ],
    feedback: false,
    links: {
      live: "",
      github: "https://github.com/CodeSahil21/VendorClause-Ai.git",
    },
  },
  {
    title: "VMC Civic Issue Monitoring System",
    slug: "vmc-civic-issue-monitoring-system",
    tagline:
      "A geo-fenced, offline-first platform to report, track, and resolve municipal civic issues with speed and accountability.",
    overview:
      "Civic-issue is a scalable MVP built for real municipal workflows and field constraints. It enables GPS-based issue reporting, automatic ward mapping with geo-fencing, role-based governance, and full issue lifecycle tracking from open to verification. The platform is designed for proactive field reporting, including offline-first operation for unstable network conditions.",
    features: [
      "GPS-based issue reporting with before/after photo uploads.",
      "Offline-first PWA workflow with local storage and background sync.",
      "Automatic ward detection and assignment using PostGIS point-in-polygon queries.",
      "Role-based access for Field Worker, Ward Engineer, Zone Officer, and Super Admin.",
      "Issue lifecycle tracking: OPEN, ASSIGNED, IN_PROGRESS, RESOLVED, VERIFIED.",
      "Map navigation handoff to Google Maps and MapMyIndia from issue details.",
      "AI-assisted issue categorization prototype using TensorFlow.js.",
    ],
    techStack: [
      "Next.js",
      "React 19",
      "TypeScript",
      "Tailwind CSS",
      "Redux Toolkit",
      "PWA",
      "Node.js",
      "Express",
      "Prisma",
      "PostgreSQL",
      "PostGIS",
      "Cloudinary",
      "TensorFlow.js",
    ],
    challenges: [
      "Ensuring reliable issue reporting in low or no-network field environments.",
      "Implementing accurate geospatial ward mapping with real-world boundary data.",
      "Designing role-specific dashboards and permissions for civic governance workflows.",
      "Maintaining traceability and accountability across the complete issue lifecycle.",
    ],
    learnings: [
      "Strengthened practical understanding of offline-first application design.",
      "Gained hands-on experience with spatial queries and geo-fencing using PostGIS.",
      "Improved skills in building role-based systems for operational workflows.",
      "Learned how to align product decisions with public-sector constraints and field realities.",
    ],
    feedback: false,
    links: {
      live: "",
      github: "https://github.com/CodeSahil21/Civic-issue.git",
    },
  },
  {
    title: "Learnit | Learning Management System",
    slug: "learnit-learning-management-system",
    tagline:
      "A full-stack LMS for role-based course delivery, progress tracking, and certificate generation.",
    overview:
      "Learnit is a modern Learning Management System built for students, mentors, and admins. It supports secure JWT-based authentication, mentor approval workflows, sequential chapter learning, progress analytics, enrollment management, and automatic PDF certificate generation for completed courses. The stack combines a TypeScript React frontend with a Node/Express backend and Prisma on PostgreSQL.",
    features: [
      "Role-based access control for Student, Mentor, and Admin users.",
      "Mentor approval workflow managed by admin users.",
      "Course and chapter management with sequential learning flow.",
      "Student enrollment management (single and bulk assignment).",
      "Progress tracking dashboards and course-level insights.",
      "Automatic completion certificate generation using PDFKit.",
      "Validation and security layers with Zod, JWT, and bcrypt.",
    ],
    techStack: [
      "React",
      "TypeScript",
      "Vite",
      "Redux Toolkit",
      "React Router",
      "Tailwind CSS",
      "shadcn/ui",
      "Node.js",
      "Express",
      "Prisma",
      "PostgreSQL",
      "Zod",
      "JWT",
      "PDFKit",
    ],
    challenges: [
      "Designing clear role boundaries and workflow permissions across students, mentors, and admins.",
      "Implementing strict sequential chapter progression without blocking user experience.",
      "Handling enrollment and progress queries efficiently for mentor and admin dashboards.",
      "Generating reliable completion certificates tied to verified course progress.",
    ],
    learnings: [
      "Strengthened full-stack architecture skills for education-focused SaaS workflows.",
      "Improved understanding of role-based authorization and protected route design.",
      "Gained deeper experience with Prisma schema design and relational progress tracking.",
      "Learned to integrate document generation into a production-style web platform.",
    ],
    feedback: false,
    links: {
      live: "",
      github: "https://github.com/CodeSahil21/Learnit.git",
    },
  },
  {
    title: "GoFleet | Real-Time Ride Platform",
    slug: "gofleet-real-time-ride-platform",
    tagline:
      "A full-stack Uber-like platform for real-time ride booking, tracking, and captain operations.",
    overview:
      "GoFleet is a ride management platform with user and captain authentication, live trip lifecycle updates, and real-time location-based collaboration between riders and captains. Built with a Next.js frontend and Node/Express backend, it uses Socket.IO for realtime communication, Prisma with PostgreSQL for data persistence, and JWT-based authentication for secure access control.",
    features: [
      "User and captain authentication with secure session handling.",
      "Real-time ride lifecycle management from creation to completion.",
      "Live tracking and mapping integration for trip visibility.",
      "Socket.IO channels for rider-captain communication updates.",
      "Captain profile and ride management workflows.",
      "Fare-aware ride flow with responsive cross-device UI.",
    ],
    techStack: [
      "Next.js",
      "React",
      "Tailwind CSS",
      "Node.js",
      "Express",
      "Prisma",
      "PostgreSQL",
      "Socket.IO",
      "JWT",
      "Google Maps API",
    ],
    challenges: [
      "Coordinating real-time event updates across riders and captains with low latency.",
      "Modeling ride state transitions safely from request to completion.",
      "Integrating map-based tracking while keeping frontend performance responsive.",
      "Maintaining auth and route protection across distributed client/server flows.",
    ],
    learnings: [
      "Improved skills in realtime system design using Socket.IO event patterns.",
      "Deepened practical experience with trip workflow modeling and state handling.",
      "Enhanced backend API design with Prisma and relational data constraints.",
      "Gained stronger understanding of map-driven user experiences and live mobility UX.",
    ],
    feedback: false,
    links: {
      live: "",
      github: "https://github.com/CodeSahil21/UberClone.git",
    },
  },
  {
    title: "Portfolio | Sahil Singh",
    slug: "portfolio",
    tagline:
      "My current portfolio showcasing projects, skills, and full-stack plus AI engineering work.",
    overview:
      "My current personal portfolio highlights my journey as a Full Stack and AI Engineer. It includes interactive features like profile view tracking, love count engagement, and modern server actions for performant, seamless user experiences.",
    features: [
      "API to track and display profile views in real-time.",
      "Love count feature to allow visitors to express appreciation for the work.",
      "Implemented server actions using the latest Next.js features.",
      "Dynamic project listing with slug-based routing for detailed pages.",
      "Mobile-responsive and optimized for all devices.",
      "Integration with MongoDB using Mongoose for efficient data management.",
    ],
    techStack: [
      "Next.js",
      "shadcn/ui",
      "MongoDB",
      "Tailwind CSS",
      "Radix UI",
      "TypeScript",
    ],
    challenges: [
      "Implementing real-time tracking for profile views efficiently.",
      "Designing and integrating a scalable database schema with Mongoose.",
      "Utilizing server actions for seamless and performant interactions.",
      "Ensuring cross-browser and device compatibility for UI components.",
    ],
    learnings: [
      "Deepened knowledge of Next.js server actions and their use cases.",
      "Gained experience in designing interactive UI components.",
      "Enhanced understanding of MongoDB operations and ORM with Mongoose.",
      "Improved ability to optimize performance for web applications.",
    ],
    feedback: true,
    links: {
      live: "",
      github: "https://github.com/CodeSahil21",
    },
  },
  {
    title: "EchoRay | AI-Powered Real-Time Code Collaboration",
    slug: "echoray-ai-code-collaboration",
    tagline:
      "A modern AI-powered collaboration platform for project management, real-time coding, chat, and instant code assistance.",
    overview:
      "EchoRay is a next-generation collaborative coding and project management platform built for teams that want to plan, build, and ship faster together. It combines live multi-user code editing, project-based chat, role-aware project controls, and integrated AI assistance within a developer-first experience powered by Monaco editor, socket-based realtime sync, and secure authentication.",
    features: [
      "Project management workflows with secure CRUD operations and role-aware access.",
      "Real-time collaborative code editing and team chat using Socket.IO.",
      "Integrated AI assistant for code generation, debugging, and task automation.",
      "Monaco editor and file-tree workflow for an IDE-like in-browser experience.",
      "Live output preview for faster iteration during collaborative sessions.",
      "JWT plus cookie-based authentication with Redis-backed performance support.",
      "Responsive modern UI with Tailwind CSS and GSAP-driven interactions.",
    ],
    techStack: [
      "Next.js",
      "React",
      "TypeScript",
      "Redux",
      "Tailwind CSS",
      "Monaco Editor",
      "GSAP",
      "Node.js",
      "Express",
      "Prisma",
      "PostgreSQL",
      "Redis",
      "Socket.IO",
      "JWT",
      "OpenAI",
      "Google Generative AI",
    ],
    challenges: [
      "Synchronizing real-time collaboration events while keeping editor state consistent across users.",
      "Designing secure role-based project permissions without disrupting team collaboration speed.",
      "Integrating AI-assisted workflows into coding sessions without adding friction to core UX.",
      "Balancing low-latency communication and system scalability across chat, editor, and preview channels.",
    ],
    learnings: [
      "Improved system design skills for real-time collaborative applications.",
      "Gained deeper practical experience with Socket.IO event architecture and state synchronization.",
      "Strengthened backend and auth design patterns using Prisma, JWT, cookies, and Redis.",
      "Learned to combine AI tooling with developer experience patterns in a production-style workflow.",
    ],
    feedback: false,
    links: {
      live: "",
      github: "https://github.com/CodeSahil21/EchoRay-.git",
    },
  },
];
